// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Daj4xs8iO_dcicU7L8oFXn1ufSxzO_g',
    appId: '1:939748137916:web:c94784cf74815f6c5969b9',
    messagingSenderId: '939748137916',
    projectId: 'junction-testing',
    authDomain: 'junction-testing.firebaseapp.com',
    storageBucket: 'junction-testing.firebasestorage.app',
    measurementId: 'G-NSWSL52N36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzJ56tzKSj39v8_U761-ReTD_aINe5kc',
    appId: '1:939748137916:android:b1001a08f76866b15969b9',
    messagingSenderId: '939748137916',
    projectId: 'junction-testing',
    storageBucket: 'junction-testing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9_dV_uRwumRcIQ9qUoxZK-h1c0bXBN4',
    appId: '1:939748137916:ios:979bd82f103341f45969b9',
    messagingSenderId: '939748137916',
    projectId: 'junction-testing',
    storageBucket: 'junction-testing.firebasestorage.app',
    iosBundleId: 'com.example.junction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI9_dV_uRwumRcIQ9qUoxZK-h1c0bXBN4',
    appId: '1:939748137916:ios:979bd82f103341f45969b9',
    messagingSenderId: '939748137916',
    projectId: 'junction-testing',
    storageBucket: 'junction-testing.firebasestorage.app',
    iosBundleId: 'com.example.junction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Daj4xs8iO_dcicU7L8oFXn1ufSxzO_g',
    appId: '1:939748137916:web:05759eb99025e7c65969b9',
    messagingSenderId: '939748137916',
    projectId: 'junction-testing',
    authDomain: 'junction-testing.firebaseapp.com',
    storageBucket: 'junction-testing.firebasestorage.app',
    measurementId: 'G-RZ8DGV3M53',
  );
}
