// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Daj4xs8iO_dcicU7L8oFXn1ufSxzO_g',
    appId: '1:944746529789:web',
    messagingSenderId: '944746529789',
    projectId: 'junction-e0625',
    authDomain: 'junction-e0625.firebaseapp.com',
    storageBucket: 'junction-e0625.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASqmjASEB7EEQrRK-RySC45IZu6f6-A7E',
    appId: '1:944746529789:android:0109c186117f845cc1cf94',
    messagingSenderId: '944746529789',
    projectId: 'junction-e0625',
    storageBucket: 'junction-e0625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzguQmJW2l8ZY5effSJ9zRrZ03i9lYpvQ',
    appId: '1:944746529789:ios:44abe864937cfd47c1cf94',
    messagingSenderId: '944746529789',
    projectId: 'junction-e0625',
    storageBucket: 'junction-e0625.firebasestorage.app',
    iosBundleId: 'com.junction.verse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzguQmJW2l8ZY5effSJ9zRrZ03i9lYpvQ',
    appId: '1:944746529789:ios:44abe864937cfd47c1cf94',
    messagingSenderId: '944746529789',
    projectId: 'junction-e0625',
    storageBucket: 'junction-e0625.firebasestorage.app',
    iosBundleId: 'com.junction.verse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Daj4xs8iO_dcicU7L8oFXn1ufSxzO_g',
    appId: '1:944746529789:web',
    messagingSenderId: '944746529789',
    projectId: 'junction-e0625',
    authDomain: 'junction-e0625.firebaseapp.com',
    storageBucket: 'junction-e0625.firebasestorage.app',
  );

}